version: '3.8'

services:
  node:
    depends_on:
      - postgres-test
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      PORT: 60051
    ports:
      - "60051:60051"

  workflow:
    depends_on:
      - postgres-test
      - scheduler
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      PORT: 60052
      WORKFLOW_API_TOKENS: admin:testtoken
    ports:
      - "60052:60052"

  scheduler:
    depends_on:
      - postgres-test
      - node
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      NODE_TARGET: node:60051
  
  postgres-test:
    image: postgres:17
    container_name: aisociety_postgres_test
    environment:
      POSTGRES_USER: aisociety
      POSTGRES_PASSWORD: aisociety
      POSTGRES_DB: aisociety_test_db
    command: ["postgres", "-c", "port=55432"]
    ports:
      - "55433:55432"

  node-test:
    depends_on:
      - node
    image: golang:1.24-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PORT=60051
      - DATABASE_URL=postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      - WORKFLOW_API_TOKENS=admin:testtoken
    command: go test -v ./services/node/...
