version: '3.8'

services:
  scheduler:
    depends_on:
      - postgres-test
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      NODE_TARGET: node-service:50054
    ports:
      - "60051:50052"

  workflow-service:
    depends_on:
      - postgres-test
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      WORKFLOW_PORT: 50052
    ports:
      - "60052:50052"

  node-service:
    depends_on:
      - postgres-test
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres-test:55432/aisociety_test_db?sslmode=disable
      NODE_PORT: 50054
    ports:
      - "60054:50054"

  
  postgres-test:
    image: postgres:17
    container_name: aisociety_postgres_test
    environment:
      POSTGRES_USER: aisociety
      POSTGRES_PASSWORD: aisociety
      POSTGRES_DB: aisociety_test_db
    command: ["postgres", "-c", "port=55432"]
    ports:
      - "55433:55432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./services/workflow/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  postgres_test_data:
