version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: aisociety_postgres
    environment:
      POSTGRES_USER: aisociety
      POSTGRES_PASSWORD: aisociety
      POSTGRES_DB: aisociety_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/workflow/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  node-service:
    build:
      context: .
      dockerfile: services/node/Dockerfile
    container_name: node_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres:5432/aisociety_db?sslmode=disable
    ports:
      - "50051:50051"

  workflow-service:
    build:
      context: .
      dockerfile: services/workflow/Dockerfile
    container_name: workflow_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres:5432/aisociety_db?sslmode=disable
      NODE_TARGET: node-service:50051
      WORKFLOW_PORT: 50052
      NODE_PORT: 50051
    ports:
      - "50052:50052"

  scheduler:
    build:
      context: .
      dockerfile: services/scheduler/Dockerfile
    container_name: scheduler
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://aisociety:aisociety@postgres:5432/aisociety_db?sslmode=disable


volumes:
  postgres_data:
